export const LOAD_LIST_OF_PEOPLE_INIT = 'app/LOAD_LIST_OF_PEOPLE_INIT';
export const LOAD_LIST_OF_PEOPLE_SUCCESS = 'app/LOAD_LIST_OF_PEOPLE_SUCCESS';
export const LOAD_LIST_OF_PEOPLE_FAILURE = 'app/LOAD_LIST_OF_PEOPLE_FAILURE';

export const LOAD_SEARCH_OF_PEOPLE_INIT = 'app/LOAD_SEARCH_OF_PEOPLE_INIT';
export const LOAD_SEARCH_OF_PEOPLE_SUCCESS = 'app/LOAD_SEARCH_OF_PEOPLE_SUCCESS';
export const LOAD_SEARCH_OF_PEOPLE_FAILURE = 'app/LOAD_SEARCH_OF_PEOPLE_FAILURE';